### PR TITLE
fixed typo in overview.md

### PR DESCRIPTION
**Pull request by Sir-Rumeh**
fixed the spelling typo in overview.md from "locoated" to "located"

### CODE REVIEW

**Comment by dovholuknf** [comment]
Any chance you could undo all the format changes? I'd hate to have the md->html engine to have issues with the differences. likely wouldn't matter but it's better to try to minimize the amount of changes in the PR.

thanks for the PR!

**Comment by Sir-Rumeh** [comment]
My Vs code has a default formatting for everytime I save any work so I
don't know if I can undo that, but I'll try.
Maybe I'll just Change the settings of the formatter to align with that of
the previous state

**Comment by dovholuknf** [comment]
The change is quite small. You could use a text editor of any kind to minimize the lines of code changed. If you are still willing - great. Otherwise I can make this update.  Still want to complete it?

**Comment by Sir-Rumeh** [comment]
Yes, please!

**Comment by dovholuknf** [comment]
Closing this issue due to inactivity. If you end up stripping all the unneeded changes, please reopen this PR.

**Pull request closed without merging**
