### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by amoghakancharla**
I've tried improving the following to this page. Kindly review them.
1. Added a clear title header for "What is OpenZiti?".
2. Changed the "An Example of an OpenZiti Overlay Network" section to use a proper markdown header and added an image title.
3. Reorganized the "In OpenZiti, You Will Find" section to use bullet points for better readability.
4. Improved formatting for links, making them more prominent.
5. Added an emoji icon (:rocket:) for the "Ready to deploy your first network?" section to make it more engaging.

### CODE REVIEW

**Comment by dovholuknf** [comment]
thanks for taking a swing at this. We're in a busy period, but hopefully me or someone else will get back to this soon. stay tuned!

**Comment by dovholuknf** [comment]
I'm so sorry to ask this, but can you rebase this branch from main? We found/fixed the issue wrt GLIBC and somehow it looks like it has conflicts now?

**Comment by amoghakancharla** [comment]
Sure, let me check that and get back to you.

**Comment by dovholuknf** [comment]
closing this pr due to age. open it back up again if you resolve the conflicts.

**Pull request closed without merging**
