### PR TITLE
Localgw

### PR DESCRIPTION
**Pull request by jlin-nf**
Add guide for using ziti-router or ziti-tunnel as local gw

### CODE REVIEW

**Comment by dovholuknf** [comment]
I'd really prefer to see us use text blocks and not screen caps for cli examples.

**Comment by jlin-nf** [comment]
> I'd really prefer to see us use text blocks and not screen caps for cli examples.

converted cli image to text

**Review by r-caamano — APPROVED** [review]

**Review by dovholuknf — APPROVED** [review]
@r-caamano approved. approving so it can merge

**Comment by dovholuknf** [comment]
I can't merge this PR. The last few commits were not signed. Unfortunately there's no 'easy' way to fix that. imo the easiest way will be to make a whole branch, merge without committing, and make a new PR with the commits signed.

**Pull request closed without merging**
