### PR TITLE
fixes to allow Vercel to build Docusaurus2 for previewing ziti-doc branches

### LINKED ISSUE #185: Use Vercel to review PRs
vercel looks to support rendering PRs for review. I'd like to be able to put a ziti-doc PR up and have it rendered in vercel for review / comments

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
@dovholuknf We should wait to merge this until ready to move Docusaurus `baseUrl` to the root route `/`, displacing DocFx. Vercel rendering fails with `"baseUrl": "/docusaurus"`.

**Review by qrkourier — COMMENTED** [review]
@dovholuknf re-enable Vercel when ready to resume testing this branch. I've added a config property in vercel.json that will silence Vercel's comments on PRs to reduce notification fatigue after this merges to main.

**Comment by qrkourier** [comment]
Summary of changes: added an option to `gendoc.sh` to take an extra step when the web host is Vercel: modify Docusaurus's baseUrl from `/docusaurus/` to `/`. This change only exists in Vercel's build environment and is necessary for the site to render in Vercel. 

Additionally, the `vercel.json` file overrides Vercel's production site options and keeps the config as code in this repo thereby making it unnecessary to properly configure overrides in Vercel UI e.g. the build command to run `gendoc.sh` with the correct options.

`gendoc.sh` was also re-organized to only require the DocFx dependencies when running in DocFx mode.

**Review by dovholuknf — APPROVED** [review]
i re-enabled it

**Pull request merged**
