### PR TITLE
Fixes and Tweaks

### PR DESCRIPTION
**Pull request by davefinger**
• Fixed GitHub and Discourse Links
• Added HotJar Tags
• Consolidated Google Analytics Tag

### CODE REVIEW

**Review by gberl002 — APPROVED** [review]

**Comment by dovholuknf** [comment]
@davefinger please fix the footer wrt "NetFoundry, Inc." --> "NetFoundry Inc."

I'd like to not change the github logo colors to pink nor the discourse logo to blue. can you use the existing ones that are branded the way they use? 
image

**Comment by dovholuknf** [comment]
it this "a joke" or copy/paste miss??? lol 
image

**Comment by dovholuknf** [comment]
Can the footer be either made to look the same as the top or maybe just remove a bunch of it? At very least the "OpenZiti" link should be removed from the footer and "documents" should be changed to "Documentation".

image

**Comment by dovholuknf** [comment]
I'd prefer the 'star us' banner to float at the top and be visible immediately. I'd rather people not have to scroll to the very very bottom to get hit with the 'star us' CTA

**Comment by dovholuknf** [comment]
I would rather this takes me down the page to the "Building Your First Network" section. Maybe call it "Start Building" or "Build a Network"?:
image

Also every section should have a link-able anchor

**Comment by davefinger** [comment]
> it this "a joke" or copy/paste miss??? lol
> image

LOL. Nope, copy and paste miss. Late night coding session. I'll add to the PR

**Comment by davefinger** [comment]
> Can the footer be either made to look the same as the top or maybe just remove a bunch of it? At very least the "OpenZiti" link should be removed from the footer and "documents" should be changed to "Documentation".
> 
> image

I'll remove the OpenZiti, and expand the documents. I'll also add a Git Started. I can't do the icons and buttons with this theme without breaking a bunch of stuff. We'll leave those off.

**Comment by davefinger** [comment]
> I would rather this takes me down the page to the "Building Your First Network" section. Maybe call it "Start Building" or "Build a Network"?: image
> 
> Also every section should have a link-able anchor

I'm fine with that. It was a placeholder while the team was on vacation. 

As for the anchors, we can add them to any section, as needed if we want to link to them.

**Comment by davefinger** [comment]
> @davefinger please fix the footer wrt "NetFoundry, Inc." --> "NetFoundry Inc."
> 
> I'd like to not change the github logo colors to pink nor the discourse logo to blue. can you use the existing ones that are branded the way they use? image

Footer is an easy fix.

The icon links at the top are an icon font, and have to be for the mobile menu to not break. Can't swap those for the images. I can make the Doc site ones match though. This will keep them inline with the Zrok and BrowZer sites as well.

**Comment by davefinger** [comment]
> I'd prefer the 'star us' banner to float at the top and be visible immediately. I'd rather people not have to scroll to the very very bottom to get hit with the 'star us' CTA

We tried this on the Zrok site and it breaks everything. The theme and that code don't play well together. We'll need to stick with the current Zrok style for now, and readdress with some sort of custom menu down the road.

**Pull request merged**
