### PR TITLE
Deployment architecture

### PR DESCRIPTION
**Pull request by dariuszSki**
ok , here we go, 1 -> 2 -> 3....go!

### CODE REVIEW

**Comment by dariuszSki** [comment]
should the lock files be ignored and added to .gitignore?

**Comment by dovholuknf** [comment]
please rename the _share* files with what they actually represent logically instead of _share. same for the images. 1.1.png isn't descriptive enough etc through 4.3.png.

per docusaurus' recommendation https://docusaurus.io/docs/static-assets static assets should be in the /static/img folder. until there's a good reason not to do that, let's put them there in properly named subfolders

**Comment by dariuszSki** [comment]
should I create deployment arch folder in /static/img to group them together?

**Comment by dovholuknf** [comment]
> should I create deployment arch folder in /static/img to group them together?

I think that makes sense. yah. you should be able to then reference them with `/img/deployment/blah.png`

**Comment by dariuszSki** [comment]
ok, updated names and moved the images to its own folder under the static/img folder.

**Comment by dovholuknf** [comment]
Kubernetes has a lovely guide to rebase. Please rebase this PR per https://raw.githubusercontent.com/kubernetes/community/master/contributors/guide/git_workflow.png

Once rebased, please make sure you run `yarn build` from the docusaurus folder, or make sure you change to the root folder and run `./gendoc.sh -cd`

Please make sure it completes successfully so I can pull and review. thanks

**Comment by dariuszSki** [comment]
I get this error
```
dsliwinski:/mnt/c/Users/dsliwinski/Repos/ziti-doc/docusaurus$ yarn build
yarn run v1.22.19
$ docusaurus build
[INFO] [en] Creating an optimized production build...
✖ Client
  Compiled with some errors in 1.59m
● Server █████████████████████████ building (64%) 1/1 entries 2380/2380 dependencies 750/750 modules 0 active 

Module not found: Error: Can't resolve '../../../_remotes/ziti-android-app/README.md' in '/mnt/c/Users/dsliwinski/Repos/ziti-doc/docusaurus/docs/quickstarts/mobile'
[ERROR] Client bundle compiled with errors therefore further build is impossible.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comman
```

**Comment by dariuszSki** [comment]
I can not locate this README file
```
import AndroidMd from '../../../_remotes/ziti-android-app/README.md';
```

**Comment by dovholuknf** [comment]
I need to spiff up the readme... Run gendoc.sh and it'll pull those dependencies

**Pull request closed without merging**
