### PR TITLE
docs: Replaced with ZITI_CTRL_EDGE_IP_OVERRIDE in hosted.md

### LINKED ISSUE #569: ZITI_EDGE_CONTROLLER_IP_OVERRIDE is incorrectly named
There is a reference to `ZITI_EDGE_CONTROLLER_IP_OVERRIDE` in the "host it anywhere" quickstart doc, but this variable is not used and should be instead referencing `ZITI_CTRL_EDGE_IP_OVERRIDE`.

### PR DESCRIPTION
**Pull request by ThaungThanHan**
In hosted.md file, I have spotted the "ZITI_EDGE_CONTROLLER_IP_OVERRIDE" variable that is reported not being used anywhere and replaced with "ZITI_CTRL_EDGE_IP_OVERRIDE" as described. Fixes: #569

### CODE REVIEW

**Comment by dovholuknf** [comment]
Thanks @ThaungThanHan. I think @gberl002 was working on this today. I'll let him comment

**Review by gberl002 — DISMISSED** [review]
Looks good, thank you for your contribution.

**Comment by dovholuknf** [comment]
oh no. looks like the commit wasn't signed... We'll probably have to just make the change ourselves unless @ThaungThanHan can make a new PR with a signed commit...

**Comment by dovholuknf** [comment]
Hi @ThaungThanHan thanks for trying again!. You're going to need to make a whole new branch. We can't accept any unverified commits and though you have signed this commit, the branch still has your first unsigned commit and the second commit is still unverified
Screenshot_20230804-060047

So you should:
* Make sure your commits show "verified"
* make a new branch
* make a verified commit
* make a new pr, or if github will let you update this pr with the new branch

Hope that helps. It's a pain, but once you do it, it's basically setup forever

**Pull request closed without merging**
