### PR TITLE
update alt server certs guide

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
This article has a scope problem. It should be renamed like "Self-Hosting the BrowZer Bootstrapper," and stop generalizing "public certificates." The current scope is not truly a "guide" because it tries to field FAQs like "do I need 3rd-party server certs on my edge APIs?" that would be moot if the guide focused on the object of configuring BrowZer.

**Comment by qrkourier** [comment]
@dovholuknf ready for review

**Comment by dovholuknf** [comment]
Really? Looks like you're just totally removing the file not "updating" it?

**Comment by qrkourier** [comment]
This rewrite was a failed attempt to partially answer [the issue about documenting bring-your-own-pki](https://github.com/openziti/ziti-doc/issues/151). We should use that issue to organize and focus efforts on the various topics the issue represents. It's a broad issue, so we should peel off pieces of that which can be addressed with a particular type of doc, like a guide, explainer, or tutorial.

**Comment by dovholuknf** [comment]
~~I don't know what the thumbs up emoji means. Is the _plan_ to remove this file entirely?~~ Your comment and mine came in at the same time...

**Review by dovholuknf — APPROVED** [review]

**Pull request merged**
